import { Users } from "lucide-react";

export const videosData = [
  {
    url: "http://res.cloudinary.com/dvf6d5bam/video/upload/v1756787079/get_1_mbs3pm.mp4",
    name: "get_1_mbs3pm",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Social", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Get Together",
    description: "A joyful celebration with friends.",
    date: "July 2024",
    location: "Grand Ballroom",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/video/upload/v1756786801/Our_beautiful_couple_Prathima_and_Raj_living_in_the_US_wanted_to_get_married_in_their_own_unique_xnivhc.mp4",
    name: "Our_beautiful_couple_Prathima_and_Raj",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Wedding", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Wedding Bliss",
    description: "A beautiful wedding ceremony with loved ones.",
    date: "June 2024",
    location: "Rose Garden",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/video/upload/v1756786800/Star_studded_engagement_of_Nithin_and_Sushmita_was_a_spectacular_evening_at_the_Prince_of_Wales_cyu1gb.mp4",
    name: "Star_studded_engagement_of_Nithin_and_Sushmita",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Engagement", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Engagement Gala",
    description: "A star-studded engagement evening.",
    date: "May 2024",
    location: "Prince of Wales Hall",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/video/upload/v1756786796/A_beautifully_curated_Upanayana_event_by_emaginationsincc_at_place_ground_recently_focused_on_c_rjhz7m.mp4",
    name: "Upanayana_Event",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Religious", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Upanayana Ceremony",
    description: "A traditional Upanayana celebration.",
    date: "April 2024",
    location: "Temple Grounds",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/video/upload/v1756786787/Bringing_Visions_to_Life_No_Matter_the_Challenge_At_Emaginations_Experience_Pvt_Ltd_we_beli_hwwnla.mp4",
    name: "Visions_Celebration",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Corporate", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Corporate Vision",
    description: "Celebrating achievements and vision.",
    date: "March 2024",
    location: "Conference Hall",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/video/upload/v1756786785/Absolut_electric_absolute_absolut_absolutenewyork_absolutevodka_absolute_absolut_absoluten_ljfko9.mp4",
    name: "Absolut_Event",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Social", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Absolute Fun",
    description: "An electrifying celebration with Absolut.",
    date: "February 2024",
    location: "Sky Lounge",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/video/upload/v1756786785/Classy_weddings_that_match_your_taste._The_wedding_reception_of_Nigel_and_Prinsha_was_all_about_yrangi.mp4",
    name: "Classy_Wedding",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Wedding", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Elegant Wedding",
    description: "A classy wedding reception.",
    date: "January 2024",
    location: "Royal Banquet Hall",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/video/upload/v1756786783/AQO-jG3q64VBMbDXw62OPk_unLNh_5EltGuYMz7jsotuKq89yi9bRkqZt7Q9eqtwdSF1SAPboIePcdTpJB80upltKgPGEO5-_r5cc0e.mp4",
    name: "Corporate_Meeting",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Corporate", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Board Meeting",
    description: "High-profile corporate meeting event.",
    date: "December 2023",
    location: "Executive Hall",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/video/upload/v1756786782/There_is_something_magical_about_two_people_taking_a_chance_to_rise_in_love_even_more_courage_xq97y2.mp4",
    name: "Magical_Moment",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Social", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Love in the Air",
    description: "A magical moment between two souls.",
    date: "November 2023",
    location: "City Park",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/video/upload/v1756786781/A_stellar_host_and_a_fun_energizer_-_Cyrus_Sahukar_made_Inspira_Annual_Awards_a_memorable_exper_aupjeb.mp4",
    name: "Inspira_Awards",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Corporate", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Award Night",
    description: "A fun-filled award ceremony.",
    date: "October 2023",
    location: "Grand Theater",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/video/upload/v1756786778/Meticulous_planning_from_concept_to_drawing_board_to_execution._We_curated_a_real_life-like_roof_wufdcj.mp4",
    name: "Event_Planning",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Corporate", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Planning Success",
    description: "From concept to execution flawlessly.",
    date: "September 2023",
    location: "Innovation Hub",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/image/upload/v1756786778/Creativity_takes_courage_spykhardseltzer_launched_in_India_..the_smoothest_and_craziest_hard_n80jvi.jpg",
    name: "Creativity_Launch",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Social", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Creative Launch",
    description: "Launching a bold and creative product.",
    date: "August 2023",
    location: "City Studio",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/video/upload/v1756786777/Where_Healing_Begins_with_Trust..._From_petals_to_precision_we_launched_sparsh_Hospital_s_new_xl69ym.mp4",
    name: "Healing_Event",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Health", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Healing Trust",
    description: "A medical launch with care and precision.",
    date: "July 2023",
    location: "Sparsh Hospital",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/video/upload/v1756786766/Walk_into_the_world_of_class_An_event_by_EmaginationsInc_imagineadot_cornerstoneakhintaresi_bvmqma.mp4",
    name: "Class_Event",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Social", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Classy Walk",
    description: "An elegant event showcasing style.",
    date: "June 2023",
    location: "Cornerstone Hall",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/image/upload/v1756786766/We_at_emaginationsinc_are_thrilled_to_share_that_We_have_Won_6_Awards_at_the_EDCA_2023_-_E_2_x3blb3.jpg",
    name: "EDCA_Awards",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Corporate", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Award Victory",
    description: "Winning 6 prestigious awards.",
    date: "May 2023",
    location: "EDCA Center",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/image/upload/v1756786766/Wishing_each_and_everyone_of_this_Great_Country_-_Peace_Progress_and_Prosperity-_the_dream_our_mrca6m.jpg",
    name: "Peace_Wishes",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Social", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Peace & Prosperity",
    description: "Wishing peace and growth to everyone.",
    date: "April 2023",
    location: "National Plaza",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/image/upload/v1756786764/With_The_Maestro_arrahman_music_musician_musically_livemusic_musicproducer_events_corpo_yn5fjt.jpg",
    name: "Maestro_Concert",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Music", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Musical Evening",
    description: "An enchanting musical performance.",
    date: "March 2023",
    location: "Concert Arena",
  },
  {
    url: "http://res.cloudinary.com/dvf6d5bam/video/upload/v1756786554/There_is_something_magical_about_two_people_taking_a_chance_to_rise_in_love_even_more_courage_xgwb7g.mp4",
    name: "Love_Magic",
    icon: Users,
    iconColor: "text-emerald-400",
    gradient: "from-emerald-500/20 to-blue-600/20",
    tag: { text: "Social", bg: "bg-emerald-500/20 text-emerald-400" },
    title: "Magical Love",
    description: "Capturing the magic of love and courage.",
    date: "February 2023",
    location: "Sunset Garden",
  },
];


